server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /health {
        proxy_pass http://backend:8080/health;
    }

    location /version {
        proxy_pass http://backend:8080/version;
    }
}