version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: bg-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/active_upstream.conf:/etc/nginx/conf.d/active_upstream.conf
    depends_on:
      - app-blue
      - app-green
    networks:
      - bg-net

  app-blue:
    image: homework3-app:${APP_VERSION:-latest}
    container_name: app-blue
    environment:
      - APP_ENV=blue
      - APP_VERSION=${APP_VERSION:-latest}
      - PORT=8080
    expose:
      - "8080"
    networks:
      - bg-net

  app-green:
    image: homework3-app:${APP_VERSION:-latest}
    container_name: app-green
    environment:
      - APP_ENV=green
      - APP_VERSION=${APP_VERSION:-latest}
      - PORT=8080
    expose:
      - "8080"
    networks:
      - bg-net

networks:
  bg-net:
    driver: bridge